apiDebug: false
restVersion: 6
timeout: 120000
dappPath: ./dapp
libPath: blockapps-sol/dist
apiUrl: /api/v1
deployFilename: ./config/minishift.deploy.yaml

nodes:
  - id: 0
    url: "http://node-strato.192.168.99.100.nip.io"
    publicKey: "6d8a80d14311c39f35f516fa664deaaaa13e85b2f7493f37f6144d86991ec012937307647bd3b9a82abe2974e1407241d54947bbb39763a4cac9f77166ad92a0"
    port: 30303
    oauth:
      appTokenCookieName: "tt_session"
      scope: "email openid"
      appTokenCookieMaxAge: 7776000000 # 90 days: 90 * 24 * 60 * 60 * 1000
      clientId: "public-dev"
      clientSecret: "d93cde7e-5de1-4f59-80d2-31017c444f0c"
      openIdDiscoveryUrl: "https://keycloak.blockapps.net/auth/realms/public/.well-known/openid-configuration"
      redirectUri: "http://localhost/api/v1/authentication/callback"
      logoutRedirectUri: "http://localhost"
